Resources:
  DraftBucket:
    Type: AWS::S3::Bucket
    Properties:
      HibernationOptions:
        Configured: true
      ImageId: "ami-08e4e35cccc6189f4"
      InstanceInitiatedShutdownBehavior: "stop"
      InstanceType: "t2.micro"
      KeyName: draft-machine-keypair
      SecurityGroupIds:
        - "sg-0eb6b38ed293117e7"
      SecurityGroups:
        - "draft-security-group"
      Tags:
        - Key: "type"
          Value: "draft"
